spring:
  datasource:
    driverClassName: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/beehive?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:123456}
  jpa:
    database-platform: ${DATABASE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: ${PORT:8080}
  //sql:
  //  init:
  //    mode: always
app:
  default:
    admin:
      password: 123456